db.createUser(
    {
        user:"user",
        pwd:"user",
        roles:[
            {
                role:"readWrite",
                db:"dec-2022-docker-chepko"
            }
        ]
    }
)